databases:
  - name: core
    type: mongo
    host: 127.0.0.1
    port: 27017
    database: nutrixhub
    username: ""
    password: ""
    tables:
      sales: client_sales

payment:
  api_key: test
  subscribing_url: test
  public_key: test
  secret_key: test
    
env: dev